services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    hostname: navidrome
    networks:
      - x_network
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_BASEURL: ""
      ND_LASTFM_SECRET: "123"
      ND_LASTFM_APIKEY: "123"
    volumes:
      - "/home/akiro/docker/navidrome/data:/data"
      - "/home/akiro/docker/navidrome/music:/music:ro"

networks:
  x_network:
    external: true