services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    hostname: navidrome

    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_BASEURL: ""
      ND_LASTFM_SECRET: "11111111111111111"
      ND_LASTFM_APIKEY: "11111111111111111"
    volumes:
      - "/home/akiro/docker/navidrome/data:/data"
      - "/home/akiro/docker/navidrome/music:/music:ro"