services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8082:80
    networks:
      - pgadmin_network
    restart: unless-stopped

  postgres_default:
    image: postgres:latest
    container_name: postgres_default
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    networks:
      - pgadmin_network
    restart: unless-stopped

networks:
  pgadmin_network:
    name: pgadmin_network
