services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3005:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /home/akiro/docker/adguard/work:/opt/adguardhome/work
      - /home/akiro/docker/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped