---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Metrics:
    - Glances:
        icon: glances.png
        href: "{{HOMEPAGE_VAR_GLANCES_URL}}"
        description: Monitoring system for home server.
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
          version: 4 # required only if running glances v4 or higher, defaults to 3
          metric: cpu
          diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
          refreshInterval: 5000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
          pointsLimit: 15 # o
    - Memory Usage:
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
          version: 4
          metric: memory
    - Network Usage:
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
          version: 4
          metric: network:eth0
    - Tasks:
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
          version: 4
          metric: process
    - CPU Temperature:
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
          version: 4
          metric: sensor:Package id 0
- Services:
    - Portainer:
        icon: docker.png
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        description: My portainer GUI
        widget:
          type: portainer
          url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
          env: 2
          key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
        description: A self-hosted monitoring tool.
        widget:
          type: uptimekuma
          url: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
          slug: "{{HOMEPAGE_VAR_UPTIME_KUMA_SLUG}}"
    - AdGuard home:
        icon: mongodb.png
        href: "{{HOMEPAGE_VAR_ADGUARD_URL}}"
        description: AdGuard Home is a network-wide software for blocking ads & tracking.
        widget:
          type: adguard
          url: "{{HOMEPAGE_VAR_ADGUARD_URL}}"
          username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
          password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"

- Media:
    - Jellyfin:
        icon: jellyfin.svg
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: Home mediaserver.
        widget:
          type: jellyfin
          url: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
          key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - Navidrome:
        icon: navidrome.png
        href: "{{HOMEPAGE_VAR_NAVIDROME_URL}}"
        description: Navidrome is an open source web-based music collection server and streamer.
        widget:
          type: navidrome
          url: "{{HOMEPAGE_VAR_NAVIDROME_URL}}"
          user: akiro
          token: 57caebd1be638a0b3c1ef4ce286c15ba
          salt: randomsalt

- Databases:
    - MongoDB:
        icon: mongodb.png
        href: "{{HOMEPAGE_VAR_MONGODB_EXPRESS_URL}}"
        description: MongoDB document databases provide high availability and easy scalability.
