---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Metrics:
    - Glances:
        icon: glances.png
        href: "{{HOMEPAGE_VAR_GLANCES_URL}}"
        description: Monitoring system for home server.
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
          version: 4 # required only if running glances v4 or higher, defaults to 3
          metric: cpu
          diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
          refreshInterval: 5000 # optional - in milliseconds, defaults to 1000 or more, depending on the metric
          pointsLimit: 15 # o
    - Memory Usage:
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
          version: 4
          metric: memory
    - Network Usage:
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
          version: 4
          metric: network:eth0
    - Tasks:
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
          version: 4
          metric: process
    - CPU Temperature:
        widget:
          type: glances
          url: "{{HOMEPAGE_VAR_GLANCES_URL}}"
          version: 4
          metric: sensor:Package id 0
- Services:
    - Portainer:
        icon: docker.png
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        description: My portainer GUI
        widget:
          type: portainer
          url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
          env: 2
          key: "{{HOMEPAGE_VAR_PORTAINER_KEY}}"
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
        description: A self-hosted monitoring tool.
        widget:
          type: uptimekuma
          url: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
          slug: "{{HOMEPAGE_VAR_UPTIME_KUMA_SLUG}}"
    - AdGuard home:
        icon: mongodb.png
        href: "{{HOMEPAGE_VAR_ADGUARD_URL}}"
        description: AdGuard Home is a network-wide software for blocking ads & tracking.
        widget:
          type: adguard
          url: "{{HOMEPAGE_VAR_ADGUARD_URL}}"
          username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
          password: "{{HOMEPAGE_VAR_ADGUARD_PASS}}"
    - Navidrome:
        icon: navidrome.png
        href: "{{HOMEPAGE_VAR_NAVIDROME_URL}}"
        description: Navidrome is an open source web-based music collection server and streamer.
        widget:
          type: navidrome
          url: "{{HOMEPAGE_VAR_NAVIDROME_URL}}"
          user: akiro
          token: 57caebd1be638a0b3c1ef4ce286c15ba
          salt: randomsalt
    - MongoDB:
        icon: mongodb.png
        href: "{{HOMEPAGE_VAR_MONGODB_EXPRESS_URL}}"
        description: MongoDB document databases provide high availability and easy scalability.
    - PostgreSQL:
        icon: postgres.png
        href: "{{HOMEPAGE_VAR_PGADMIN_URL}}"
        description: PostgreSQL Tools.
    - Neo4j:
        icon: neo4j.png
        href: "{{HOMEPAGE_VAR_NEO4J_URL}}"
        description: Neo4j is a graph database management system (GDBMS) developed by Neo4j Inc.
    - CoinMarketCup:
        icon: bitcoin.png
        href: https://coinmarketcap.com/
        description: Crypto pricing and information.
        widget:
          type: coinmarketcap
          currency: USD # Optional
          symbols: [BTC, SOL, TRX]
          key: 3ff74387-0a6e-4e72-8742-d63376601304
          defaultinterval: 7d # Optional
    #- Gitea:
    #    icon: gitea.png
    #    href: "{{HOMEPAGE_VAR_GITEA_URL}}"
    #    description: Gitea enables the creation and management of repositories based on Git.
    #    widget:
    #      type: gitea
    #      url: "{{HOMEPAGE_VAR_GITEA_URL}}"
    #      key: "{{HOMEPAGE_VAR_GITEA_API_TOKEN}}"
    - Nextcloud:
        icon: nextcloud.png
        href: "{{HOMEPAGE_VAR_NEXTCLOUD_URL}}"
        description: Nextcloud is a suite of client-server software for creating and using file hosting services.
        widget:
          type: nextcloud
          url: "{{HOMEPAGE_VAR_NEXTCLOUD_URL}}"
          username: "{{HOMEPAGE_VAR_NC_USERNAME}}"
          password: "{{HOMEPAGE_VAR_NC_TOKEN}}"

